# Generated by Django 4.1.3 on 2023-05-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_age_user_city_user_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
