# Generated by Django 4.1.3 on 2023-05-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.FileField(upload_to='books')),
                ('book_title', models.CharField(max_length=100)),
                ('book_description', models.TextField()),
                ('book_author', models.CharField(max_length=100)),
                ('book_price', models.IntegerField()),
                ('visibility', models.BooleanField(default=True)),
                ('year_of_publish', models.DateField(blank=True)),
            ],
        ),
    ]
