# Generated by Django 4.1.3 on 2023-05-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_books_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book',
            field=models.FileField(upload_to='media/books'),
        ),
    ]
